services:
  - type: web
    name: news-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GITHUB_TOKEN
        sync: false
    plan: free
    autoDeploy: true
